ALTER TABLE VERTRAG DROP CONSTRAINT VRTRAGMIETOBJEKTID
ALTER TABLE VERTRAG DROP CONSTRAINT VERTRAGmieterfirma
ALTER TABLE RESERVATION_STELLPLATZ DROP CONSTRAINT RSRVTNSTLSTLLPLTZD
ALTER TABLE RESERVATION_STELLPLATZ DROP CONSTRAINT RSRVTNSTLLPLmtrfrm
ALTER TABLE RESERVATION_STELLPLATZ DROP CONSTRAINT RSRVTNSTLLPmtrprsn
ALTER TABLE vertrag_mieter DROP CONSTRAINT vrtragmieterprsnid
ALTER TABLE vertrag_mieter DROP CONSTRAINT vrtrgmietervrtrgid
ALTER TABLE vertrag_bewohner DROP CONSTRAINT vrtrgbewohnerprsnd
ALTER TABLE vertrag_bewohner DROP CONSTRAINT vrtrgbwohnervrtrgd
DROP TABLE NN_PERSON
DROP TABLE MIETOBJEKT
DROP TABLE PERSON
DROP TABLE VERTRAG
DROP TABLE STELLPLATZ
DROP TABLE RESERVATION_STELLPLATZ
DROP TABLE vertrag_mieter
DROP TABLE vertrag_bewohner
