-- Löschen der Spalte zum Referenzieren einer Firma
alter table reservation_stellplatz drop column mieter_firma;

-- Neue Spalte zum Speichern des Typen eines Person -> Default: Bewohner
alter table person add column person_typ INTEGER NOT NULL DEFAULT 0;

-- Längen der Spalten in der Tabelle reservation_stellplatz setzen
alter table reservation_stellplatz alter bemerkung set data type VARCHAR(500);

-- Neue Entity RAUM
CREATE TABLE RAUM (
  ID BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, 
  BEZEICHNUNG VARCHAR(50), 
  VERSION BIGINT,
  PRIMARY KEY (ID));

-- Neue Entity RESERVATION_RAUM
CREATE TABLE RESERVATION_RAUM (
  ID BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, 
  ANONYM SMALLINT DEFAULT 0, 
  beginn_datum DATE NOT NULL, 
  BEMERKUNG VARCHAR(500), 
  BEZAHLT SMALLINT DEFAULT 0 NOT NULL, 
  EMAIL VARCHAR(100), 
  end_datum_exklusiv DATE NOT NULL, 
  kosten FLOAT NOT NULL, 
  NAME VARCHAR(100), 
  reservation_datum DATE NOT NULL, 
  VERSION BIGINT, 
  WOHNUNGNR INTEGER, 
  anzahl_personen INTEGER NOT NULL,
  mieter_person BIGINT, 
  RAUM_ID BIGINT NOT NULL, 
  PRIMARY KEY (ID));
  
ALTER TABLE RESERVATION_RAUM ADD CONSTRAINT RSRVTNRMRMD FOREIGN KEY (RAUM_ID) REFERENCES RAUM (ID);
ALTER TABLE RESERVATION_RAUM ADD CONSTRAINT RSRVTNRMmtrprsn FOREIGN KEY (mieter_person) REFERENCES PERSON (ID);